### ISSUE TITLE
SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by bom-sankar** [davidjeddy/ui-testing-jest-puppetteer#4]
I follow this to fix the issue 
[https://stackoverflow.com/questions/51554366/jest-securityerror-localstorage-is-not-available-for-opaque-origins](Link)

I just update the package.json with 
`"jest": {
    "verbose": true,
    "testURL": "http://localhost/"
  }`

**Comment by Jaaap** [comment]
Is it expected that you still get the `SecurityError: localStorage is not available for opaque origins` error when you add `"verbose": true, "testURL": "http://localhost/"` to the jest config?

I also get it when i run your facebook/twitter/google examples.
